spring:
  application:
    name: backend
  datasource:
    url: jdbc:sqlite:${sqlite.path:data/financeless.db}
    username: root
    password: root
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    enabled: true
    user: root
    password: root
    url: jdbc:sqlite:${sqlite.path:data/financeless.db}
    locations: classpath:db/migration
    baseline-on-migrate: true
    check-location: true
management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:4200"
        allowed-methods: "GET,POST,OPTIONS"
        allowed-headers: "*"
sql:
  init:
    mode: never