spring:
  application:
    name: backend
  datasource:
    url: jdbc:sqlite:data/financeless.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect